#!/bin/bash
#PBS -N IzmailovaH
#PBS -S /bin/bash
#PBS -l walltime=00:08:00
#PBS -l nodes=3:ppn=4
#PBS -d /home/student/FS18/FS2-x1/Izmailova/HelmholtzEquationSolver

cat $PBS_NODEFILE

mpirun -np 12 ./Helmholtz 6
